image: privacybydesign/node_yarn:latest

stages:
  - build

before_script:
  - set -euxo pipefail

irma-core:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 10 year
    paths:
      - irma-core
  script:
    - cd irma-core
    - npm install --only=prod

irma-client:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 10 year
    paths:
      - plugins/irma-client
  script:
    - cd plugins/irma-client
    - npm install --only=prod

irma-console:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 10 year
    paths:
      - plugins/irma-console
  script:
    - cd plugins/irma-console
    - npm install --only=prod

irma-dummy:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 10 year
    paths:
      - plugins/irma-dummy
  script:
    - cd plugins/irma-dummy
    - npm install --only=prod

irma-web:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 10 year
    paths:
      - plugins/irma-web
  script:
    - cd plugins/irma-web
    - npm install --only=prod

irma-css:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 10 year
    paths:
      - irma-css
  script:
    - cd irma-css
    - npm install
    - npm run release
    - rm -rf node_modules

irma-popup:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 10 year
    paths:
      - plugins/irma-popup
  script:
    - cd plugins/irma-popup
    - npm install --only=prod

irma-frontend:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 10 year
    paths:
      - irma-frontend
  script:
    - cd irma-frontend
    - npm install
    - npm run release
    - rm -rf node_modules

irma-legacy:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 10 year
    paths:
      - irma-legacy
  script:
    - cd irma-legacy
    - npm install
    - npm run release
    - rm -rf node_modules
