image: privacybydesign/node_yarn:latest

stages:
  - build

before_script:
  - set -euxo pipefail

irma-core:
  stage: build
  artifacts:
    paths:
      - irma-core
  script:
    - cd irma-core
    - npm install

irma-client:
  stage: build
  artifacts:
    paths:
      - plugins/irma-client
  script:
    - cd plugins/irma-client
    - npm install

irma-console:
  stage: build
  artifacts:
    paths:
      - plugins/irma-console
  script:
    - cd plugins/irma-console
    - npm install

irma-dummy:
  stage: build
  artifacts:
    paths:
      - plugins/irma-dummy
  script:
    - cd plugins/irma-dummy
    - npm install

irma-web:
  stage: build
  artifacts:
    paths:
      - plugins/irma-web
  script:
    - cd plugins/irma-web
    - npm install

irma-css:
  stage: build
  artifacts:
    paths:
      - irma-css
  script:
    - cd irma-css
    - npm install
    - npm run release

# Other artifacts can yet be added when first packages are in npm
